### ISSUE TITLE
Using shared elements

### ISSUE THREAD

**Issue by AviadKlein10** [vinc3m1/RoundedImageView#181] opened 2017-03-16 13:15 UTC
Hi really great library thank you!
I'm using shared elements but the image after transition get strached and vise versa.
What can I make sure the image using its own size and not the size of the first image?

**Comment by vinc3m1** [comment] 2017-04-03 16:52
Seems like duplicate of #164. Reopen if not.  Also examples would help, it's s not clear what you're describing with just words.

**Closed by vinc3m1** 2017-04-03 16:52 UTC
