### ISSUE TITLE
Black border around src image appears if there's no rounded corners set.

### ISSUE THREAD

**Issue by Lingviston** [vinc3m1/RoundedImageView#119] opened 2015-08-17 08:27 UTC
I use RoundedImageView to display images from network (using UIL). It has mutable background set in code. For some reason if I don't set any non-null rounded corner I can see 2 black borders: one around src image centered within ImageView and another one around whole ImageView. I have to explicitly disable border to avoid this issue (no border is set by me).

**Comment by guilhermesgb** [comment] 2015-08-18 21:49
This might be a duplicate of another open issue (#115).

**Comment by vinc3m1** [comment] 2015-08-23 07:14
Yep same issue.

**Closed by vinc3m1** 2015-08-23 07:14 UTC
