### ISSUE TITLE
 android:scaleType="centerCrop" not working anymore

### ISSUE THREAD

**Issue by timmolter** [vinc3m1/RoundedImageView#129] opened 2015-10-30 11:54 UTC
I updated from 1.3.1 to 2.2.0 and the center cropping isn't working any more. Is this a bug or do I need to update anything else? Here's my XML:

    <com.makeramen.roundedimageview.RoundedImageView xmlns:app="http://schemas.android.com/apk/res-auto"
        android:id="@+id/rouded_image"
        android:layout_width="0px"
        android:layout_height="wrap_content"
        android:layout_weight="72"
        android:src="@drawable/cam64"
        android:scaleType="centerCrop"
        app:riv_border_width="0dip"
        app:riv_corner_radius="5dp"
        app:riv_mutate_background="true"
        app:riv_oval="false" />

**Comment by vinc3m1** [comment] 2015-10-30 17:39
Isn't working how exactly? I wonder if it's related to the 0 layout width.

**Comment by dboyjq** [comment] 2015-11-10 11:24
![untitled](https://cloud.githubusercontent.com/assets/8596985/11061202/47747868-87e0-11e5-98af-a58f05df45eb.png)
It shows oval even I set oval to false. If I set scaleType to fitCenter it shows circle but that's different:

    <com.makeramen.roundedimageview.RoundedImageView
        xmlns:app="http://schemas.android.com/apk/res-auto"
        app:riv_corner_radius="40dp"
        app:riv_mutate_background="true"
        app:riv_oval="false"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginBottom="5dp"
        android:scaleType="centerCrop"/>

**Comment by dboyjq** [comment] 2015-11-10 11:28
![views_shared_contact_default_icon](https://cloud.githubusercontent.com/assets/8596985/11061318/350d6bc0-87e1-11e5-8006-c9ce99c47557.png)
Here is the original image

**Comment by dboyjq** [comment] 2015-11-10 11:35
fixXY also has the similar issue. Looks like if the view is not square, fixXY and centerCrop cannot make circle image even oval is false?

**Comment by vinc3m1** [comment] 2015-11-10 15:35
@dboyq that's expected behavior. Oval + equal widths = circle. Oval=false just means you get rounded corners, doesn't make it circle.

**Comment by dboyjq** [comment] 2015-11-11 06:03
@vinc3m1 thx for confirming. May I request a feature that we can set a "alwaysCircle" to true and force drawing a circle image?

**Comment by vinc3m1** [comment] 2015-11-27 19:50
@dboyjq please open a new issue as this is unrelated to the original. Will be deleting all these comments to stay on topic.

**Comment by vinc3m1** [comment] 2015-11-27 19:51
Closing due to lack of details around "isn't working".

**Closed by vinc3m1** 2015-11-27 19:51 UTC

**Comment by mhgk** [comment] 2015-12-16 11:32
I use Gradle to import your project.
The scale types, for instance centercrop doesnt center on the object. I saw another issues where it seemed like it was fixed.  Is it fixed or do i this xml not correct?

 <com.makeramen.roundedimageview.RoundedImageView
            android:layout_width="80dp"
            android:layout_height="100dp"
            android:layout_marginTop="10dp"
            android:id="@+id/employee_image_id"
            android:layout_gravity="center_horizontal"
            android:scaleType="centerCrop"
            app:riv_corner_radius="15dip"
            app:riv_border_width="2dip"
            app:riv_border_color="@color/picture_frame"
            app:riv_mutate_background="true"
            app:riv_tile_mode="repeat"
            app:riv_oval="true"/>
